package ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2018-07-07T16:12:07.744+02:00
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "ProcessusAchatMetierService", 
                  wsdlLocation = "http://DESKTOP-28RSBAP:8080/2018.07.04.processus.achat.ws.ejb/ProcessusAchatMetier?wsdl",
                  targetNamespace = "http://ws/") 
public class ProcessusAchatMetierService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws/", "ProcessusAchatMetierService");
    public final static QName ProcessusAchatMetierPort = new QName("http://ws/", "ProcessusAchatMetierPort");
    static {
        URL url = null;
        try {
            url = new URL("http://DESKTOP-28RSBAP:8080/2018.07.04.processus.achat.ws.ejb/ProcessusAchatMetier?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ProcessusAchatMetierService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://DESKTOP-28RSBAP:8080/2018.07.04.processus.achat.ws.ejb/ProcessusAchatMetier?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ProcessusAchatMetierService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ProcessusAchatMetierService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProcessusAchatMetierService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ProcessusAchatMetierService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ProcessusAchatMetierService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ProcessusAchatMetierService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ProcessusAchatMetier
     */
    @WebEndpoint(name = "ProcessusAchatMetierPort")
    public ProcessusAchatMetier getProcessusAchatMetierPort() {
        return super.getPort(ProcessusAchatMetierPort, ProcessusAchatMetier.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProcessusAchatMetier
     */
    @WebEndpoint(name = "ProcessusAchatMetierPort")
    public ProcessusAchatMetier getProcessusAchatMetierPort(WebServiceFeature... features) {
        return super.getPort(ProcessusAchatMetierPort, ProcessusAchatMetier.class, features);
    }

}
